-- 注释掉下在面的三行代码可以禁用所有插件, 只有在数组enabled中的插件会被加载
if true then
    return {}
end
-- 只有在下面列表中的插件才会被加载
local enabled = {
    -- "vimtex",
    -- "hop.nvim",
    -- "LuaSnip",
    -- "bufferize.vim",
    -- "sqlite.lua",
    -- "yanky.nvim",
    "vim-startuptime",
    -- "aurora",
    -- "bufferize.vim",
    -- "cmp-buffer",
    -- "cmp-dictionary",
    -- "cmp_luasnip",
    -- "cmp-nvim-lsp",
    -- "cmp-path",
    -- "cmp-vimtex",
    -- "Comment.nvim",
    -- "conform.nvim",
    -- "CopilotChat.nvim",
    -- "copilot.lua",
    -- "copilot-lualine",
    -- "dark_flat.nvim",
    -- "hltermpaste.vim",
    -- "hop.nvim",
    -- "indent-blankline.nvim",
    -- "kanagawa.nvim",
    -- "lazy.nvim",
    -- "log",
    -- "lsp-progress.nvim",
    -- "lualine.nvim",
    -- "LuaSnip",
    -- "mason-lspconfig.nvim",
    -- "mason.nvim",
    -- "menu",
    -- "mini.notify",
    -- "monochrome.nvim",
    -- "neotab.nvim",
    -- "nightfox.nvim",
    -- "nord.nvim",
    -- "nvim",
    -- "nvim-autopairs",
    -- "nvim-cmp",
    -- "nvim-colorizer.lua",
    -- "nvim-lspconfig",
    -- "nvim-notify",
    -- "nvim-quietlight",
    -- "nvim-surround",
    -- "nvim-tree.lua",
    -- "nvim-web-devicons",
    -- "onedarkpro.nvim",
    -- "one_monokai.nvim",
    -- "persisted.nvim",
    -- "plenary.nvim",
    -- "registers",
    -- "snacks.nvim",
    -- "sqlite.lua",
    -- "SyntaxAttr.vim",
    -- "telescope-fzf-native.nvim",
    -- "telescope.nvim",
    -- "themery.nvim",
    -- "tokyonight.nvim",
    -- "ultisnips-snippets",
    -- "vim-altercmd",
    -- "vim-lastplace",
    -- "vim-matchup",
    -- "vim-searchindex",
    -- "vimtex",
    -- "volt",
    -- "vscode-latex-snippets",
    -- "yanky.nvim",
    -- "zephyrium",
    -- "zephyr-nvim",
    -- "vim-startuptime",
}
local config = require("lazy.core.config")
config.options.defaults.cond = function(plugin)
    return vim.tbl_contains(enabled, plugin.name)
end
return {}
